import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
      <nav>
          <div className="max-w-7xl mx-auto flex justify-between items-center p-4">
            <h1 className="text-lg font-bold">BARBER APP</h1>
            <div className="flex gap-4 text-zinc-500">
              <Link href={"/"} className=" hover:text-white">Home</Link>
              <Link href={"/barberia"} className=" hover:text-white">Barber</Link>
              <Link href={"/barbero"} className=" hover:text-white">Barbero</Link>
              <Link href={"/cortes"} className=" hover:text-white">Cortes</Link>
              <Link href={"/productos"} className=" hover:text-white">Productos</Link>
            </div>
          </div>
      </nav>
      <main className="flex-1">
        {children}
      </main>
      <footer className="w-full border-t border-zinc-200 dark:border-zinc-800">
        <div className="max-w-7xl mx-auto flex justify-between items-center p-4">
          <p>©Copyright 2026</p>
          <p>3erTiempo</p>
        </div>
      </footer>
      </body>
    </html>
  );
}
