import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
      <nav className="bg-mauve-900 text-white px-20">
          <section className="w-full flex justify-between tems-center p-12">
            <article className="flex">
              <h1 className="text-lg font-bold text-amber-400">Cortes & Navajas</h1>
            </article>
            <article className="flex items-center gap-6 text-zinc-300">
              <Link href={"/"} className=" hover:text-white">Home</Link>
              <Link href={"/barberia"} className=" hover:text-white">Barber</Link>
              <Link href={"/barbero"} className=" hover:text-white">Barberos</Link>
              <Link href={"/cortes"} className=" hover:text-white">Cortes</Link>
              <Link href={"/productos"} className=" hover:text-white">Productos</Link>
            </article>
          </section>
      </nav>
      <main className="flex-1">
        {children}
      </main>
      <footer className="w-full border-t py-8 bg-mauve-950 text-zinc-500 border-zinc-200 dark:border-zinc-800">
        <div className="max-w-7xl mx-auto flex justify-between items-center p-4">
          <p>©Copyright 2026</p>
          <p>3erTiempo</p>
        </div>
      </footer>
      </body>
    </html>
  );
}
