import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="flex gap-4 p-5 bg-black text-white">
          <Link href="/">Inicio</Link>
          <Link href="/barberia">Barberia</Link>
          <Link href="/cortes">Cortes</Link>
          <Link href="/barbero">Barbero</Link>
        </nav>

        {children}
        <footer className="p-1 bg-gray-200">
          Footer
        </footer>
        </body>
    </html>
  );
}
